dist: xenial
language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8

before_install: cd varana
install:
  - pip install -r requirements.txt
  - pip install .

script: pytest
