#!/usr/bin/env bash

INSTALL_DIR=/usr/local
PROJECT_DIR=variability-analyser

GREEN='\033[0;32m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'


clear
printf ":: Variability-analyser installation ::\n\n"
printf "Install dir: (default ${BOLD}${INSTALL_DIR}${RESET}, press Enter): "
read answer

if [ "${answer}" != "" ]
then
    answer=${answer%/}
    eval answer=${answer}
    INSTALL_DIR=${answer}
fi

printf "Your install location: ${BOLD}${INSTALL_DIR}/${PROJECT_DIR}${RESET}\n"

while read -r -p "Abort? [y/N] " response
do
    case "$response" in
        [yY])
            printf "Installation aborted\n"
            exit
            ;;
        [nN])
            break
            ;;
        "")
            break
            ;;
        *)
            continue
            ;;
    esac
done

mkdir ${INSTALL_DIR}/${PROJECT_DIR} 2> /dev/null

if [ $? -ne 0 ]
then
    if [ -e ${INSTALL_DIR}/${PROJECT_DIR} ]
    then
        tmp=${BOLD}${INSTALL_DIR}/${PROJECT_DIR}${RESET}${RED}
        printf "${RED}ERROR: Directory ${tmp} already exists${RESET}\n"
        exit
    elif [ `id -u` -ne 0 ]
    then
        printf "${RED}ERROR: Run this script as root or with sudo${RESET}\n"
        exit
    fi
fi


cd varana
python3 setup.py install
cd ..


if [ $? -ne 0 ]
then
    if [ `id -u` -ne 0 ]
    then
        printf "${RED}ERROR: Run this script as root or with sudo${RESET}\n"
        exit
    else
        printf "${RED}ERROR: Cannot install the varana module${RESET}\n"
        exit
    fi
fi


curl -O http://helas.astro.uni.wroc.pl/data/source/fnpeaks.tar.gz
tar -xzvf fnpeaks.tar.gz
cd FNPEAKS/
make
mv fnpeaks ..
cd ..
rm -rf FNPEAKS fnpeaks.tar.gz


printf "VARANA_PATH='${INSTALL_DIR}/${PROJECT_DIR}'\n" > .variability.rc
printf "export VARANA_PATH\n" >> .variability.rc
printf "PATH=${PATH}:${INSTALL_DIR}/${PROJECT_DIR}\n" >> .variability.rc

cp -rp var_analyser.sh lib var.config ${INSTALL_DIR}/${PROJECT_DIR}/.
mv fnpeaks .variability.rc ${INSTALL_DIR}/${PROJECT_DIR}/.

tmp=${HOME}/.bashrc
rc_file=${INSTALL_DIR}/${PROJECT_DIR}/.variability.rc
printf "\nif [ -e ${rc_file} ]; then\n    source ${rc_file}\nfi\n" >> ${tmp}
sleep 1
. ${tmp}
printf "\n${GREEN}Variability-analyser${RESET} has been successfully installed!\n"
